CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE,
    logo_url VARCHAR(500), industry VARCHAR(100), website VARCHAR(300),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE interview_experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    role_name VARCHAR(150) NOT NULL, level_name VARCHAR(50),
    exp_year INTEGER NOT NULL, exp_month INTEGER,
    difficulty VARCHAR(20) NOT NULL, outcome VARCHAR(20), rounds INTEGER,
    description TEXT, verified_email VARCHAR(255) NOT NULL,
    token_jti VARCHAR(255) NOT NULL UNIQUE,
    upvotes INTEGER NOT NULL DEFAULT 0,
    exp_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experience_id BIGINT NOT NULL REFERENCES interview_experiences(id) ON DELETE CASCADE,
    question_text TEXT NOT NULL, category VARCHAR(50) NOT NULL,
    topic VARCHAR(100), round_number INTEGER,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_exp_company ON interview_experiences(company_id);
CREATE INDEX idx_exp_status  ON interview_experiences(exp_status);
CREATE INDEX idx_q_experience ON questions(experience_id);
INSERT INTO companies (name,slug,logo_url,industry,website) VALUES
('Amazon','amazon','https://logo.clearbit.com/amazon.com','Technology','https://amazon.com'),
('Google','google','https://logo.clearbit.com/google.com','Technology','https://google.com'),
('Microsoft','microsoft','https://logo.clearbit.com/microsoft.com','Technology','https://microsoft.com'),
('Meta','meta','https://logo.clearbit.com/meta.com','Technology','https://meta.com'),
('Netflix','netflix','https://logo.clearbit.com/netflix.com','Technology','https://netflix.com'),
('Flipkart','flipkart','https://logo.clearbit.com/flipkart.com','E-commerce','https://flipkart.com'),
('Razorpay','razorpay','https://logo.clearbit.com/razorpay.com','Fintech','https://razorpay.com'),
('Swiggy','swiggy','https://logo.clearbit.com/swiggy.com','FoodTech','https://swiggy.com'),
('Zomato','zomato','https://logo.clearbit.com/zomato.com','FoodTech','https://zomato.com'),
('Uber','uber','https://logo.clearbit.com/uber.com','Technology','https://uber.com');
